# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Prabhakar Shenoy's playground
email: prabs7311@gmail.com
description: > # this means to ignore newlines until "baseurl:"
 When your only tool is a hammer, all problems start looking like nails.
url: "http://rasayana.github.io" # the base hostname & protocol for your site
twitter_username: prabs7311
github_username: rasayana

# Build settings
markdown: kramdown
