# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Prabhakar Shenoy's playground
email: prabs7311@gmail.com
description: > # this means to ignore newlines until "baseurl:"
“Take up one idea. Make that one idea your life; dream of it; think of it; live on that idea. Let the brain, the body, muscles, nerves, every part of your body be full of that idea, and just leave every other idea alone. This is the way to success, and this is the way great spiritual giants are produced.”
― Swami Vivekananda, Vedanta Philosophy: Lectures by the Swami Vivekananda on Raja Yoga Also Pantanjali's Yoga Aphorisms, with Commentaries, and Glossary of Sa   
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://rasayana.github.io" # the base hostname & protocol for your site
twitter_username: prabs7311
github_username: rasayana

# Build settings
markdown: kramdown
